export const defaultQueue: SpotifyAlbumTrack[] = [
  {
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/79z0Z8E5uY2Fc7HO4VGerm',
        },
        href: 'https://api.spotify.com/v1/artists/79z0Z8E5uY2Fc7HO4VGerm',
        id: '79z0Z8E5uY2Fc7HO4VGerm',
        name: 'Elephant Tree',
        type: 'artist',
        uri: 'spotify:artist:79z0Z8E5uY2Fc7HO4VGerm',
      },
    ],
    available_markets: [],
    disc_number: 1,
    duration_ms: 73735,
    explicit: false,
    external_urls: {
      spotify: 'https://open.spotify.com/track/4jfEVENvL5XS0FWmDAvRe3',
    },
    href: 'https://api.spotify.com/v1/tracks/4jfEVENvL5XS0FWmDAvRe3',
    id: '4jfEVENvL5XS0FWmDAvRe3',
    is_local: false,
    name: 'Wake.Repeat This is not real but a test (Intro)',
    preview_url: null,
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:4jfEVENvL5XS0FWmDAvRe3',
  },
  {
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/79z0Z8E5uY2Fc7HO4VGerm',
        },
        href: 'https://api.spotify.com/v1/artists/79z0Z8E5uY2Fc7HO4VGerm',
        id: '79z0Z8E5uY2Fc7HO4VGerm',
        name: 'Elephant Tree',
        type: 'artist',
        uri: 'spotify:artist:79z0Z8E5uY2Fc7HO4VGerm',
      },
    ],
    available_markets: [],
    disc_number: 1,
    duration_ms: 260729,
    explicit: false,
    external_urls: {
      spotify: 'https://open.spotify.com/track/6R6IEQQ0n1IkdSlNlNWjY6',
    },
    href: 'https://api.spotify.com/v1/tracks/6R6IEQQ0n1IkdSlNlNWjY6',
    id: '6R6IEQQ0n1IkdSlNlNWjY6',
    is_local: false,
    name: 'Sails',
    preview_url: null,
    track_number: 2,
    type: 'track',
    uri: 'spotify:track:6R6IEQQ0n1IkdSlNlNWjY6',
  },
  {
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/79z0Z8E5uY2Fc7HO4VGerm',
        },
        href: 'https://api.spotify.com/v1/artists/79z0Z8E5uY2Fc7HO4VGerm',
        id: '79z0Z8E5uY2Fc7HO4VGerm',
        name: 'Elephant Tree',
        type: 'artist',
        uri: 'spotify:artist:79z0Z8E5uY2Fc7HO4VGerm',
      },
    ],
    available_markets: [],
    disc_number: 1,
    duration_ms: 398951,
    explicit: false,
    external_urls: {
      spotify: 'https://open.spotify.com/track/5y19LIgfHm60HBTPrOc1Ph',
    },
    href: 'https://api.spotify.com/v1/tracks/5y19LIgfHm60HBTPrOc1Ph',
    id: '5y19LIgfHm60HBTPrOc1Ph',
    is_local: false,
    name: 'Faceless',
    preview_url: null,
    track_number: 3,
    type: 'track',
    uri: 'spotify:track:5y19LIgfHm60HBTPrOc1Ph',
  },
  {
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/79z0Z8E5uY2Fc7HO4VGerm',
        },
        href: 'https://api.spotify.com/v1/artists/79z0Z8E5uY2Fc7HO4VGerm',
        id: '79z0Z8E5uY2Fc7HO4VGerm',
        name: 'Elephant Tree',
        type: 'artist',
        uri: 'spotify:artist:79z0Z8E5uY2Fc7HO4VGerm',
      },
    ],
    available_markets: [],
    disc_number: 1,
    duration_ms: 439461,
    explicit: false,
    external_urls: {
      spotify: 'https://open.spotify.com/track/1cme8gydNcO7BuidqEWcsb',
    },
    href: 'https://api.spotify.com/v1/tracks/1cme8gydNcO7BuidqEWcsb',
    id: '1cme8gydNcO7BuidqEWcsb',
    is_local: false,
    name: 'Exit the Soul',
    preview_url: null,
    track_number: 4,
    type: 'track',
    uri: 'spotify:track:1cme8gydNcO7BuidqEWcsb',
  },
  {
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/79z0Z8E5uY2Fc7HO4VGerm',
        },
        href: 'https://api.spotify.com/v1/artists/79z0Z8E5uY2Fc7HO4VGerm',
        id: '79z0Z8E5uY2Fc7HO4VGerm',
        name: 'Elephant Tree',
        type: 'artist',
        uri: 'spotify:artist:79z0Z8E5uY2Fc7HO4VGerm',
      },
    ],
    available_markets: [],
    disc_number: 1,
    duration_ms: 224201,
    explicit: false,
    external_urls: {
      spotify: 'https://open.spotify.com/track/1InGMREy9WcVhmRMHmUIeH',
    },
    href: 'https://api.spotify.com/v1/tracks/1InGMREy9WcVhmRMHmUIeH',
    id: '1InGMREy9WcVhmRMHmUIeH',
    is_local: false,
    name: 'The Fall Chorus',
    preview_url: null,
    track_number: 5,
    type: 'track',
    uri: 'spotify:track:1InGMREy9WcVhmRMHmUIeH',
  },
  {
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/79z0Z8E5uY2Fc7HO4VGerm',
        },
        href: 'https://api.spotify.com/v1/artists/79z0Z8E5uY2Fc7HO4VGerm',
        id: '79z0Z8E5uY2Fc7HO4VGerm',
        name: 'Elephant Tree',
        type: 'artist',
        uri: 'spotify:artist:79z0Z8E5uY2Fc7HO4VGerm',
      },
    ],
    available_markets: [],
    disc_number: 1,
    duration_ms: 396381,
    explicit: false,
    external_urls: {
      spotify: 'https://open.spotify.com/track/5RDWexbmyuUKkTMjuZIurq',
    },
    href: 'https://api.spotify.com/v1/tracks/5RDWexbmyuUKkTMjuZIurq',
    id: '5RDWexbmyuUKkTMjuZIurq',
    is_local: false,
    name: 'Bird',
    preview_url: null,
    track_number: 6,
    type: 'track',
    uri: 'spotify:track:5RDWexbmyuUKkTMjuZIurq',
  },
  {
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/79z0Z8E5uY2Fc7HO4VGerm',
        },
        href: 'https://api.spotify.com/v1/artists/79z0Z8E5uY2Fc7HO4VGerm',
        id: '79z0Z8E5uY2Fc7HO4VGerm',
        name: 'Elephant Tree',
        type: 'artist',
        uri: 'spotify:artist:79z0Z8E5uY2Fc7HO4VGerm',
      },
    ],
    available_markets: [],
    disc_number: 1,
    duration_ms: 375733,
    explicit: false,
    external_urls: {
      spotify: 'https://open.spotify.com/track/18qzdod9JqatvjJDiUmz3Q',
    },
    href: 'https://api.spotify.com/v1/tracks/18qzdod9JqatvjJDiUmz3Q',
    id: '18qzdod9JqatvjJDiUmz3Q',
    is_local: false,
    name: 'Wasted',
    preview_url: null,
    track_number: 7,
    type: 'track',
    uri: 'spotify:track:18qzdod9JqatvjJDiUmz3Q',
  },
  {
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/79z0Z8E5uY2Fc7HO4VGerm',
        },
        href: 'https://api.spotify.com/v1/artists/79z0Z8E5uY2Fc7HO4VGerm',
        id: '79z0Z8E5uY2Fc7HO4VGerm',
        name: 'Elephant Tree',
        type: 'artist',
        uri: 'spotify:artist:79z0Z8E5uY2Fc7HO4VGerm',
      },
    ],
    available_markets: [],
    disc_number: 1,
    duration_ms: 430982,
    explicit: false,
    external_urls: {
      spotify: 'https://open.spotify.com/track/7dQRROJz1pNelIGM4yPiUU',
    },
    href: 'https://api.spotify.com/v1/tracks/7dQRROJz1pNelIGM4yPiUU',
    id: '7dQRROJz1pNelIGM4yPiUU',
    is_local: false,
    name: 'Broken Nails',
    preview_url: null,
    track_number: 8,
    type: 'track',
    uri: 'spotify:track:7dQRROJz1pNelIGM4yPiUU',
  },
];
